[project]
name = "day_24"
version = "0.1.0"
description = "Add a short description here"
authors = ["Jeff Pursell <jpursell@gmail.com>"]
channels = ["conda-forge"]
platforms = ["win-64"]

[tasks]

[dependencies]
sympy = ">=1.12,<2"
jupyterlab = ">=4.0.11,<4.1"
holoviews = ">=1.18.1,<1.19"
numpy = ">=1.26.3,<1.27"
pyarrow = ">=14.0.2,<14.1"
