[project]
name = "aoc23-python"
version = "0.1.0"
description = "Add a short description here"
authors = ["Jeff Pursell <jpursell@gmail.com>"]
channels = ["conda-forge"]
platforms = ["win-64", "osx-64"]

[tasks]

[dependencies]
jupyterlab = ">=4.0.9,<4.1"
holoviews = ">=1.18.1,<1.19"
networkx = ">=3.2.1,<3.3"
numpy = ">=1.26.2,<1.27"
pandas = ">=2.1.4,<2.2"
